#!/usr/bin/env bun
/**
 * Build orchestrator for the cvault CLI.
 *
 * Bakes the active host's config URLs into `src/buildInfo.ts` BEFORE
 * running `bun build --compile`, then ALWAYS resets `src/buildInfo.ts`
 * to empty defaults on exit so the working copy stays clean (the file
 * is gitignored after first commit, but a polluted working copy would
 * still break dev runs and confuse future builds).
 *
 * Usage:
 *   bun run scripts/build.ts <bun-target> [--outfile <path>]
 *
 * Where <bun-target> is one of:
 *   bun-darwin-arm64
 *   bun-darwin-x64
 *   bun-linux-x64
 *   bun-linux-arm64
 *
 * Env vars consulted (same precedence as the runtime config resolver):
 *   CVAULT_CONVEX_URL          → falls back to VITE_CONVEX_URL
 *   CVAULT_FRONTEND_API_URL    → falls back to CLERK_FRONTEND_API_URL
 *   CVAULT_DASHBOARD_URL       (no fallback)
 *
 * Bun loads `.env.local` automatically when invoked from the repo root,
 * so running `bun run scripts/build.ts bun-darwin-arm64` from the cli/
 * dir picks up the dev URLs without extra setup.
 */
import { writeFileSync } from 'node:fs'
import { join, resolve as pathResolve } from 'node:path'

export interface BuildDefaults {
  convexUrl: string
  frontendApiUrl: string
  dashboardUrl: string
}

export const EMPTY_BUILD_DEFAULTS: BuildDefaults = {
  convexUrl: '',
  frontendApiUrl: '',
  dashboardUrl: '',
}

const SUPPORTED_TARGETS = ['bun-darwin-arm64', 'bun-darwin-x64', 'bun-linux-x64', 'bun-linux-arm64'] as const
type BunTarget = (typeof SUPPORTED_TARGETS)[number]

function isBunTarget(value: string): value is BunTarget {
  return (SUPPORTED_TARGETS as readonly string[]).includes(value)
}

function defaultOutfileFor(target: BunTarget): string {
  // Bun targets follow `bun-<os>-<arch>`; strip the "bun-" prefix for
  // the binary basename so artifacts are just "cvault-darwin-arm64".
  const suffix = target.replace(/^bun-/, '')
  return `dist/cvault-${suffix}`
}

/**
 * Read URL config from a process-env-like object, applying the same
 * precedence as the runtime resolver (CVAULT_* > repo aliases). Missing
 * values become empty strings so the resulting `BuildDefaults` has a
 * stable shape that won't trip up `pickString` at runtime.
 */
export function resolveBuildDefaultsFromEnv(env: Record<string, string | undefined>): BuildDefaults {
  return {
    convexUrl: env.CVAULT_CONVEX_URL ?? env.VITE_CONVEX_URL ?? '',
    frontendApiUrl: env.CVAULT_FRONTEND_API_URL ?? env.CLERK_FRONTEND_API_URL ?? '',
    dashboardUrl: env.CVAULT_DASHBOARD_URL ?? '',
  }
}

function escapeSingleQuoted(value: string): string {
  // Generated literals use single quotes; escape any embedded single
  // quotes plus backslashes so the output is always valid TypeScript.
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

/**
 * Write a `buildInfo.ts` module exporting the given BUILD_DEFAULTS. The
 * generated file mirrors the hand-authored placeholder in shape (so
 * imports stay type-safe) but with the build-host's resolved URLs.
 */
export function writeBuildInfo(targetPath: string, defaults: BuildDefaults): void {
  const c = escapeSingleQuoted(defaults.convexUrl)
  const f = escapeSingleQuoted(defaults.frontendApiUrl)
  const d = escapeSingleQuoted(defaults.dashboardUrl)
  const content =
    `/**\n` +
    ` * AUTO-GENERATED by scripts/build.ts. Do not edit by hand.\n` +
    ` *\n` +
    ` * On a clean working copy this file holds three empty strings; the\n` +
    ` * build orchestrator overwrites it with resolved URLs immediately\n` +
    ` * before running \`bun build --compile\` and resets it on exit. See\n` +
    ` * scripts/build.ts for details.\n` +
    ` */\n` +
    `export const BUILD_DEFAULTS = {\n` +
    `  convexUrl: '${c}',\n` +
    `  frontendApiUrl: '${f}',\n` +
    `  dashboardUrl: '${d}',\n` +
    `} as const\n`
  writeFileSync(targetPath, content, 'utf8')
}

interface RunBunBuildArgs {
  target: BunTarget
  outfile: string
  cwd: string
}

async function runBunBuild({ target, outfile, cwd }: RunBunBuildArgs): Promise<number> {
  // Mirror the existing build:* scripts in package.json: minify,
  // sourcemap, bytecode, target, outfile.
  const args = [
    'build',
    '--compile',
    '--minify',
    '--sourcemap',
    '--bytecode',
    `--target=${target}`,
    './src/index.ts',
    '--outfile',
    outfile,
  ]
  // eslint-disable-next-line no-console
  console.log(`[build] bun ${args.join(' ')}`)
  const proc = Bun.spawn(['bun', ...args], { cwd, stdout: 'inherit', stderr: 'inherit' })
  return await proc.exited
}

interface OrchestrateArgs {
  target: BunTarget
  outfile: string
  cliDir: string
  env: Record<string, string | undefined>
}

async function orchestrate({ target, outfile, cliDir, env }: OrchestrateArgs): Promise<number> {
  const buildInfoPath = join(cliDir, 'src', 'buildInfo.ts')
  const defaults = resolveBuildDefaultsFromEnv(env)

  // Belt-and-suspenders: if the user kills the process mid-build (^C,
  // SIGTERM), still reset buildInfo.ts so they don't end up with dev
  // URLs leaked into source. The try/finally below covers normal
  // success/failure paths.
  const resetOnSignal = (): void => {
    try {
      writeBuildInfo(buildInfoPath, EMPTY_BUILD_DEFAULTS)
    } catch {
      /* best-effort during signal handling — surface nothing to stdout */
    }
    process.exit(130) // standard SIGINT exit code
  }
  process.on('SIGINT', resetOnSignal)
  process.on('SIGTERM', resetOnSignal)

  try {
    writeBuildInfo(buildInfoPath, defaults)
    return await runBunBuild({ target, outfile, cwd: cliDir })
  } finally {
    writeBuildInfo(buildInfoPath, EMPTY_BUILD_DEFAULTS)
    process.off('SIGINT', resetOnSignal)
    process.off('SIGTERM', resetOnSignal)
  }
}

interface ParsedArgs {
  target: BunTarget
  outfile: string
}

function parseArgs(argv: ReadonlyArray<string>): ParsedArgs {
  const positional = argv.filter((a) => !a.startsWith('--'))
  const target = positional[0]
  if (!target || !isBunTarget(target)) {
    throw new Error(
      `Usage: bun run scripts/build.ts <target> [--outfile <path>]\n` +
        `Supported targets: ${SUPPORTED_TARGETS.join(', ')}`
    )
  }
  const outfileFlagIdx = argv.indexOf('--outfile')
  const outfile =
    outfileFlagIdx >= 0 && argv[outfileFlagIdx + 1] ? argv[outfileFlagIdx + 1]! : defaultOutfileFor(target)
  return { target, outfile }
}

// Avoid running orchestrate() when the file is imported by tests. Bun's
// `import.meta.main` is true only when the script is invoked directly
// via `bun run scripts/build.ts ...`, false when imported.
if (import.meta.main) {
  const { target, outfile } = parseArgs(process.argv.slice(2))
  // The orchestrator runs from the cli/ directory regardless of where
  // the user invoked `bun run` from — paths in package.json resolve
  // relative to package.json's location anyway.
  const cliDir = pathResolve(import.meta.dir, '..')
  const exitCode = await orchestrate({ target, outfile, cliDir, env: process.env })
  process.exit(exitCode)
}
