/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMachinesRouteImport } from './routes/dashboard/machines'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardSettingsEmailsRouteImport } from './routes/dashboard/settings/emails'
import { Route as DashboardSettingsDomainsRouteImport } from './routes/dashboard/settings/domains'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardMachinesRoute = DashboardMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/machines.lazy').then((d) => d.Route),
)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/audit.lazy').then((d) => d.Route),
)
const DashboardSettingsEmailsRoute = DashboardSettingsEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashboardSettingsRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings/emails.lazy').then((d) => d.Route),
)
const DashboardSettingsDomainsRoute =
  DashboardSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => DashboardSettingsRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/domains.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/machines': typeof DashboardMachinesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/domains': typeof DashboardSettingsDomainsRoute
  '/dashboard/settings/emails': typeof DashboardSettingsEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/machines': typeof DashboardMachinesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/domains': typeof DashboardSettingsDomainsRoute
  '/dashboard/settings/emails': typeof DashboardSettingsEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/machines': typeof DashboardMachinesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/domains': typeof DashboardSettingsDomainsRoute
  '/dashboard/settings/emails': typeof DashboardSettingsEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/audit'
    | '/dashboard/machines'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/domains'
    | '/dashboard/settings/emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audit'
    | '/dashboard/machines'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/domains'
    | '/dashboard/settings/emails'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/audit'
    | '/dashboard/machines'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/domains'
    | '/dashboard/settings/emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/machines': {
      id: '/dashboard/machines'
      path: '/machines'
      fullPath: '/dashboard/machines'
      preLoaderRoute: typeof DashboardMachinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/emails': {
      id: '/dashboard/settings/emails'
      path: '/emails'
      fullPath: '/dashboard/settings/emails'
      preLoaderRoute: typeof DashboardSettingsEmailsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/domains': {
      id: '/dashboard/settings/domains'
      path: '/domains'
      fullPath: '/dashboard/settings/domains'
      preLoaderRoute: typeof DashboardSettingsDomainsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsDomainsRoute: typeof DashboardSettingsDomainsRoute
  DashboardSettingsEmailsRoute: typeof DashboardSettingsEmailsRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsDomainsRoute: DashboardSettingsDomainsRoute,
  DashboardSettingsEmailsRoute: DashboardSettingsEmailsRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardMachinesRoute: typeof DashboardMachinesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardMachinesRoute: DashboardMachinesRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
