/**
 * AUTO-GENERATED by scripts/build.ts. Do not edit by hand.
 *
 * On a clean working copy this file holds three empty strings; the
 * build orchestrator overwrites it with resolved URLs immediately
 * before running `bun build --compile` and resets it on exit. See
 * scripts/build.ts for details.
 */
export const BUILD_DEFAULTS = {
  convexUrl: '',
  frontendApiUrl: '',
  dashboardUrl: '',
} as const
